name: Deploy to GitHub Pages

on:
  # 每次推送到 main 分支时触发
  push:
    branches: [ master ]
  # 允许在 Actions 标签页手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，允许部署到 Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许并发部署，跳过正在进行的部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 根据你的本地 node 版本调整
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Vite 默认构建输出目录是 dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4