/**
 * Terraforming task resolver - computes available projects given planet state.
 *
 * Data source: terraforming.json (generated by x4_data_processor.py)
 */

export interface TerraformingStat {
  id: string
  nameId: string
  name?: string
  default: number
  dynamic: boolean
  icon: string
  ranges: Array<{
    start?: number
    end: number
    state: number
    rgb: string
    descriptionId: string
    description?: string
    habitable?: boolean
  }>
}

export interface TerraformingProjectGroup {
  id: string
  nameId: string
  name?: string
}

export interface TerraformingCluster {
  id: string
  macro: string
  partName: string
  initialStats: Record<string, number>
  projectIds: string[]
  removedStats?: string[]
  objectives?: ClusterObjective[]
  values?: Record<string, string>
  variableTexts?: Record<string, { source: string; replaces: Array<{ from: string; to: string }> }>
}

export interface ClusterObjective {
  step: number
  action: string
  textId: string
  encyclopedia?: string
  completedVariable?: string
  textReplaces?: Array<{ from: string; to: string }>
}

export interface TerraformingProject {
  id: string
  group: string
  nameId: string
  name?: string
  descriptionId: string
  description?: string
  duration: number | null
  repeatCooldown: number | null  // null=one-time, 0=repeatable(no cooldown), >0=repeatable(with cooldown)
  resilient: boolean
  chance: number
  version: string | null
  research: string | null
  conditions: StatCondition[]
  effects: StatEffect[]
  sideEffects: SideEffect[]
  resources: ProjectResources
  deliveries: Delivery[]
  rebates: Rebate[]
  removedProjects: string[]
  blockedProjects: string[]
  blockedGroups: string[]
  predecessors: Predecessor[]
}

export interface StatCondition {
  stat: string
  min?: number
  max?: number
  minvalue?: number
  maxvalue?: number
  usesStateBounds?: boolean
  usesValueBounds?: boolean
}

export interface StatEffect {
  stat: string
  change?: number
  value?: number
  min?: number
  max?: number
}

export interface SideEffect {
  chance: number
  setback: number
  project?: string | null
  stat?: string | null
  change?: number | null
  beneficial: boolean
  textId?: string | null
}

export interface ProjectResources {
  price: number
  pricescale?: string
  payout?: number
  minWares?: number
  maxWares?: number
  maxPrice?: number
  wares: Array<{ ware: string; amount: number }>
}

export interface Delivery {
  macro: string
  amount: number
  buildDuration: number
}

export interface Rebate {
  ware?: string | null
  wareGroup?: string | null
  value: number
}

export interface Predecessor {
  ref: string
  type: 'project' | 'group'
  any: boolean
}

export interface TerraformingData {
  stats: TerraformingStat[]
  projectGroups: TerraformingProjectGroup[]
  projects: TerraformingProject[]
  clusters: TerraformingCluster[]
}

export interface TerraformingState {
  stats: Record<string, number>
  completedProjects: Map<string, number>
}

export interface TaskNode {
  id: string
  name: string
  group: string
  available: boolean
  blockedReason?: string
  effects: string
  predecessors: Predecessor[]
  children: TaskNode[]
  groupIndex?: number
}

export interface TaskTree {
  roots: TaskNode[]
  blocked: TaskNode[]
  groups: Map<string, TaskNode[]>
  groupOrder: string[]
  projectMap: Map<string, TerraformingProject>
  groupNames: Map<string, string>
}

function fmtEffect(e: StatEffect): string {
  if (e.value !== undefined) return `${e.stat}=${e.value}`
  if (e.change === undefined) return `${e.stat}`
  const sign = e.change >= 0 ? '+' : ''
  let s = `${sign}${e.change} ${e.stat}`
  if (e.min !== undefined) s += ` (min: ${e.min})`
  if (e.max !== undefined) s += ` (max: ${e.max})`
  return s
}

export function getSortedRanges(stat: TerraformingStat): TerraformingStat['ranges'] {
  const sorted = [...stat.ranges].sort((a, b) => a.end - b.end)
  let nextStart = 0
  return sorted.map(range => {
    const start = range.start ?? nextStart
    nextStart = range.end + 1
    return { ...range, start }
  })
}

export function getCurrentRange(
  stat: TerraformingStat,
  value: number,
): TerraformingStat['ranges'][number] | null {
  const ranges = getSortedRanges(stat)
  for (const range of ranges) {
    const start = range.start ?? 0
    if (value >= start && value <= range.end) return range
  }
  return ranges.length > 0 ? ranges[ranges.length - 1]! : null
}

function inferConditionMode(
  condition: StatCondition,
  stat: TerraformingStat | undefined,
): 'state' | 'value' {
  if (condition.usesValueBounds || condition.minvalue !== undefined || condition.maxvalue !== undefined) {
    return 'value'
  }
  if (condition.usesStateBounds) return 'state'
  if (!stat) return 'value'
  const ranges = getSortedRanges(stat)
  const maxState = Math.max(...ranges.map(r => r.state))
  if ((condition.min ?? -Infinity) > maxState || (condition.max ?? -Infinity) > maxState) {
    return 'value'
  }
  return 'state'
}

const GROUP_EMOJI: Record<string, string> = {
  power: '⚡',
  industry: '🏭',
  cleanup: '☢️',
  water: '💧',
  atmosphere: '🫧',
  biosphere: '🌱',
  food_staple: '🌾',
  food_luxury: '🍷',
  housing: '🏠',
  amenities: '🎪',
  training: '🎖️',
  economy: '💰',
  xenon: '👾',
  events: '⚡',
  special: '🔧',
}

function groupLabel(group: string, groupNames: Map<string, string>, i18nLookup?: I18nLookup): string {
  const emoji = GROUP_EMOJI[group] || ''
  const nameId = groupNames.get(group) || group
  const name = i18nLookup ? (i18nLookup(nameId) || nameId) : nameId
  return emoji ? `${emoji} ${name}` : name
}

export function resolveAvailableTasks(
  cluster: TerraformingCluster,
  state: TerraformingState,
  data: TerraformingData,
): TaskTree {
  const projectMap = new Map<string, TerraformingProject>()
  const groupNames = new Map<string, string>()

  for (const pg of data.projectGroups) {
    groupNames.set(pg.id, pg.nameId || pg.name || pg.id)
  }

  // Filter projects in this cluster
  const clusterProjectIds = new Set(cluster.projectIds)
  const clusterProjects: TerraformingProject[] = []
  for (const p of data.projects) {
    projectMap.set(p.id, p)
    if (clusterProjectIds.has(p.id)) {
      clusterProjects.push(p)
    }
  }

  // Build dependency graph
  const blocks = new Map<string, TaskNode>()
  for (const p of clusterProjects) {
    const node = evaluateProject(p, state, projectMap, clusterProjects, data.stats)
    blocks.set(p.id, node)
  }

  // Build tree: top-level nodes have no mandatory (non-any) project predecessors
  const roots: TaskNode[] = []
  const blocked: TaskNode[] = []
  const allChildren = new Set<string>()

  for (const [id, node] of blocks) {
    const hasMandatoryProjectPred = node.predecessors.some(
      p => {
        if (p.type !== 'project' || p.any || !clusterProjectIds.has(p.ref)) return false
        const parent = blocks.get(p.ref)
        return parent?.group === node.group
      }
    )
    if (!hasMandatoryProjectPred) {
      if (!allChildren.has(id)) {
        if (node.available) {
          roots.push(node)
        } else {
          blocked.push(node)
        }
      }
    }
  }

  // Wire up parent-child (only for non-any project predecessors that exist in cluster)
  for (const [id, node] of blocks) {
    for (const pred of node.predecessors) {
      if (pred.type !== 'project' || pred.any || !clusterProjectIds.has(pred.ref)) continue
      const parent = blocks.get(pred.ref)
      if (parent && parent.id !== id && parent.group === node.group) {
        parent.children.push(node)
        allChildren.add(id)
      }
    }
  }

  // Collect blocked nodes not already in tree
  const blockedSet = new Set(blocked.map(n => n.id))
  for (const [id, node] of blocks) {
    if (allChildren.has(id)) continue
    const isRoot = roots.some(r => r.id === id)
    if (isRoot) continue
    if (blockedSet.has(id)) continue
    if (!node.available) {
      blocked.push(node)
      blockedSet.add(id)
    } else {
      roots.push(node)
    }
  }

  // Collect by group
  const groups = new Map<string, TaskNode[]>()
  for (const node of blocks.values()) {
    const groupList = groups.get(node.group) || []
    groupList.push(node)
    groups.set(node.group, groupList)
  }

  return {
    roots,
    blocked,
    groups,
    groupOrder: data.projectGroups.map(g => g.id),
    projectMap,
    groupNames,
  }
}

function evaluateProject(
  project: TerraformingProject,
  state: TerraformingState,
  projectMap: Map<string, TerraformingProject>,
  clusterProjects: TerraformingProject[],
  stats: TerraformingStat[],
): TaskNode {
  const name = project.name || project.nameId
  const effectsStr = project.effects.map(fmtEffect).join(', ')
  const blockedReasons: string[] = []

  for (const c of project.conditions) {
    const currentVal = state.stats[c.stat]
    if (currentVal === undefined) continue
    const statDef = stats.find(s => s.id === c.stat)
    const mode = inferConditionMode(c, statDef)
    if (mode === 'value') {
      const minValue = c.minvalue ?? c.min
      const maxValue = c.maxvalue ?? c.max
      if (minValue !== undefined && currentVal < minValue) {
        blockedReasons.push(`${c.stat} >= ${minValue} (current: ${currentVal})`)
      }
      if (maxValue !== undefined && currentVal > maxValue) {
        blockedReasons.push(`${c.stat} <= ${maxValue} (current: ${currentVal})`)
      }
      continue
    }

    if (!statDef) continue
    const currentRange = getCurrentRange(statDef, currentVal)
    const currentState = currentRange?.state
    if (currentState === undefined) continue
    if (c.min !== undefined && currentState < c.min) {
      blockedReasons.push(`${c.stat} state >= ${c.min} (current: ${currentState}, value: ${currentVal})`)
    }
    if (c.max !== undefined && currentState > c.max) {
      blockedReasons.push(`${c.stat} state <= ${c.max} (current: ${currentState}, value: ${currentVal})`)
    }
  }

  for (const cp of clusterProjects) {
    const completed = (state.completedProjects.get(cp.id) ?? 0) > 0
    if (completed && cp.removedProjects.includes(project.id)) {
      blockedReasons.push(`depends: ${cp.name || cp.nameId} (removed)`)
    }
    const cpRemoved = clusterProjects.some(
      cp2 => (state.completedProjects.get(cp2.id) ?? 0) > 0 && cp2.removedProjects.includes(cp.id)
    )
    if (!completed && !cpRemoved && cp.blockedProjects.includes(project.id)) {
      blockedReasons.push(`depends: ${cp.name || cp.nameId} (blocking)`)
    }
    if (!completed && !cpRemoved && cp.blockedGroups.includes(project.group)) {
      blockedReasons.push(`depends: ${cp.name || cp.nameId} (blocking_group)`)
    }
  }

  const clusterPids = new Set(clusterProjects.map(p => p.id))

  const projectPreds = project.predecessors.filter(p => {
    if (p.type !== 'project') return false
    return clusterPids.has(p.ref)
  })
  const anyPreds = projectPreds.filter(p => p.any)
  const allPreds = projectPreds.filter(p => !p.any)
  const unmetProjectPreds: Predecessor[] = []

  if (anyPreds.length > 0) {
    const anyMet = anyPreds.some(p => (state.completedProjects.get(p.ref) ?? 0) > 0)
    if (!anyMet) {
      unmetProjectPreds.push(...anyPreds)
    }
  }

  for (const pred of allPreds) {
    if ((state.completedProjects.get(pred.ref) ?? 0) <= 0) {
      unmetProjectPreds.push(pred)
    }
  }

  if (unmetProjectPreds.length > 0) {
    const refs = unmetProjectPreds.map(p => {
      const pp = projectMap.get(p.ref)
      return pp ? (pp.name || pp.nameId) : p.ref
    })
    const hasAnyPreds = anyPreds.length > 0
    const hasAllPreds = allPreds.length > 0
    if (hasAnyPreds && !hasAllPreds) {
      blockedReasons.push(`depends_any: ${refs.join(' | ')}`)
    } else if (!hasAnyPreds && hasAllPreds) {
      blockedReasons.push(`depends_all: ${refs.join(' | ')}`)
    } else {
      blockedReasons.push(`depends: ${refs.join(' | ')}`)
    }
  }

  return {
    id: project.id,
    name,
    group: project.group,
    available: blockedReasons.length === 0,
    blockedReason: blockedReasons.length > 0 ? blockedReasons.join('; ') : undefined,
    effects: effectsStr,
    predecessors: project.predecessors.filter(p => p.type === 'group' || clusterPids.has(p.ref)),
    children: [],
  }
}

export function printTaskTree(tree: TaskTree, i18nLookup?: I18nLookup): string {
  const lines: string[] = []

  const groupOrder = tree.groupOrder.filter(g => tree.groups.has(g))
  for (const g of tree.groups.keys()) {
    if (!groupOrder.includes(g)) groupOrder.push(g)
  }

  let groupIdx = 0
  for (const group of groupOrder) {
    const nodes = tree.groups.get(group)
    if (!nodes) continue

    const label = groupLabel(group, tree.groupNames, i18nLookup)
    lines.push(label)

    const sorted = sortNodes(nodes)

    for (let i = 0; i < sorted.length; i++) {
      const node = sorted[i]!
      const isLast = i === sorted.length - 1
      const prefix = isLast ? '└──' : '├──'
      const status = node.available ? '' : ' [BLOCKED]'
      const effects = node.effects ? `  (${node.effects})` : ''
      const repeat = getRepeatLabel(node.id, tree.projectMap)
      const deps = getDependencyLabel(node, tree.projectMap, i18nLookup)
      const displayName = i18nLookup
        ? (i18nLookup(tree.projectMap.get(node.id)?.nameId || '') || node.name)
        : node.name
      lines.push(`  ${prefix} ${displayName}${effects}${repeat}${status}`)
      if (deps) {
        lines.push(`  ${isLast ? '    ' : '│   '}  ${deps}`)
      }
      if (!node.available && node.blockedReason) {
        const reasonLines = node.blockedReason.split('; ')
        for (const r of reasonLines) {
          const translated = translateBlockedReason(r, tree.projectMap, tree.groupNames, i18nLookup)
          lines.push(`  ${isLast ? '    ' : '│   '}  └─ ⛔ ${translated}`)
        }
      }
    }

    groupIdx++
    if (groupIdx < groupOrder.length) lines.push('')
  }

  return lines.join('\n')
}

function sortNodes(nodes: TaskNode[]): TaskNode[] {
  return [...nodes].sort((a, b) => {
    if (a.available !== b.available) return a.available ? -1 : 1
    return a.name.localeCompare(b.name)
  })
}

export type I18nLookup = (key: string) => string

export function resolveTerraformingText(
  textId: string,
  data: TerraformingData,
  i18nLookup: I18nLookup,
): string {
  if (textId.startsWith('{') && textId.endsWith('}')) {
    return i18nLookup(textId) || textId
  }

  const statMatch = textId.match(/^terraforming\.stat\.(\w+)\.name$/)
  if (statMatch) {
    const statId = statMatch[1]!
    const stat = data.stats.find(s => s.id === statId)
    const i18nKey = stat?.nameId
    if (i18nKey) {
      const resolved = i18nLookup(i18nKey)
      if (resolved && resolved !== i18nKey) return resolved
    }
    return stat?.name || statId
  }

  const projMatch = textId.match(/^terraforming\.project\.(\w+)\.name$/)
  if (projMatch) {
    const projId = projMatch[1]!
    const proj = data.projects.find(p => p.id === projId)
    const i18nKey = proj?.nameId
    if (i18nKey) {
      const resolved = i18nLookup(i18nKey)
      if (resolved && resolved !== i18nKey) return resolved
    }
    return proj?.name || projId
  }

  return textId
}

export function resolveWithReplaces(
  text: string,
  replaces: Array<{ from: string; to: string }> | undefined,
  data: TerraformingData,
  i18nLookup: I18nLookup,
): string {
  let result = text
  if (replaces) {
    for (const r of replaces) {
      const resolvedTo = resolveTerraformingText(r.to, data, i18nLookup)
      result = result.replace(r.from, resolvedTo)
    }
  }
  return result
}

export function printObjectives(
  cluster: TerraformingCluster,
  data: TerraformingData,
  i18nLookup: I18nLookup,
): string {
  const lines: string[] = []
  const objs = cluster.objectives
  if (!objs || objs.length === 0) {
    lines.push('(无任务目标)')
    return lines.join('\n')
  }

  lines.push('任务目标:')
  for (const obj of objs) {
    let text = resolveTerraformingText(obj.textId, data, i18nLookup)
    text = resolveWithReplaces(text, obj.textReplaces, data, i18nLookup)

    const actionLabel = ACTION_LABELS[obj.action] || obj.action
    const step = String(obj.step).padStart(2, ' ')
    lines.push(`  ${step}. [${actionLabel}] ${text}`)
  }
  return lines.join('\n')
}

const ACTION_LABELS: Record<string, string> = {
  'objective.relocate': '迁移总部',
  'objective.neutralize': '消除威胁',
  'objective.build_project': '建设改造项目',
  'objective.build_housing': '建设住宅',
  'objective.build_module': '建设空间站模块',
  'objective.destroy': '摧毁目标',
  'objective.custom': '自定义目标',
}

function getRepeatLabel(projectId: string, projectMap: Map<string, TerraformingProject>): string {
  const proj = projectMap.get(projectId)
  if (!proj) return ''
  if (proj.repeatCooldown === null) return ' [一次性]'
  if (proj.repeatCooldown === 0) return ' [可重复]'
  return ` [冷却: ${proj.repeatCooldown}s]`
}

function getDependencyLabel(
  node: TaskNode,
  projectMap: Map<string, TerraformingProject>,
  i18nLookup?: I18nLookup,
): string {
  if (node.predecessors.length === 0) return ''
  const labels = node.predecessors.map(p => {
    if (p.type === 'group') return `[组: ${resolveGroupName(p.ref, i18nLookup)}]`
    const pp = projectMap.get(p.ref)
    const raw = pp ? (pp.name || pp.nameId) : p.ref
    if (i18nLookup && pp?.nameId) return i18nLookup(pp.nameId) || raw
    return raw
  })
  const prefix = node.predecessors[0]!.any ? '⟸ 任一: ' : '⟸ '
  return prefix + labels.join(' | ')
}

function translateBlockedReason(
  reason: string,
  projectMap: Map<string, TerraformingProject>,
  _groupNames: Map<string, string>,
  i18nLookup?: I18nLookup,
): string {
  if (reason.startsWith('depends: ')) {
    const rest = reason.slice('depends: '.length)
    const parts = rest.split(' | ')
    const translated = parts.map(p => {
      if (p.startsWith('group: ')) {
        const gName = p.slice('group: '.length)
        return `[组: ${resolveGroupName(gName, i18nLookup)}]`
      }
      for (const proj of projectMap.values()) {
        if ((proj.name || proj.nameId) === p) {
          if (i18nLookup && proj.nameId) return i18nLookup(proj.nameId) || p
          return p
        }
      }
      return p
    }).join(' | ')
    return `需要: ${translated}`
  }
  return reason
}

function resolveGroupName(groupId: string, i18nLookup?: I18nLookup): string {
  if (!i18nLookup) return groupId
  const resolved = i18nLookup(groupId)
  if (resolved && resolved !== groupId) return resolved
  return groupId
}
