/**
 * Terraforming task resolver - computes available projects given planet state.
 *
 * Data source: terraforming.json (generated by x4_data_processor.py)
 */

export interface TerraformingStat {
  id: string
  nameId: string
  name?: string
  default: number
  dynamic: boolean
  icon: string
  ranges: Array<{
    end: number
    state: number
    rgb: string
    descriptionId: string
    description?: string
    habitable?: boolean
  }>
}

export interface TerraformingProjectGroup {
  id: string
  nameId: string
  name?: string
}

export interface TerraformingCluster {
  id: string
  macro: string
  partName: string
  initialStats: Record<string, number>
  projectIds: string[]
  objectives?: ClusterObjective[]
  values?: Record<string, string>
  variableTexts?: Record<string, { source: string; replaces: Array<{ from: string; to: string }> }>
}

export interface ClusterObjective {
  step: number
  action: string
  textId: string
  encyclopedia?: string
  completedVariable?: string
  textReplaces?: Array<{ from: string; to: string }>
}

export interface TerraformingProject {
  id: string
  group: string
  nameId: string
  name?: string
  descriptionId: string
  description?: string
  duration: number | null
  repeatCooldown: number | null  // null=one-time, 0=repeatable(no cooldown), >0=repeatable(with cooldown)
  resilient: boolean
  chance: number
  version: string | null
  research: string | null
  conditions: StatCondition[]
  effects: StatEffect[]
  sideEffects: SideEffect[]
  resources: ProjectResources
  deliveries: Delivery[]
  rebates: Rebate[]
  removedProjects: string[]
  blockedProjects: string[]
  blockedGroups: string[]
  predecessors: Predecessor[]
}

export interface StatCondition {
  stat: string
  min?: number
  max?: number
}

export interface StatEffect {
  stat: string
  change?: number
  value?: number
  min?: number
  max?: number
}

export interface SideEffect {
  chance: number
  setback: number
  project?: string | null
  stat?: string | null
  change?: number | null
  beneficial: boolean
  textId?: string | null
}

export interface ProjectResources {
  price: number
  pricescale?: string
  payout?: number
  minWares?: number
  maxWares?: number
  maxPrice?: number
  wares: Array<{ ware: string; amount: number }>
}

export interface Delivery {
  macro: string
  amount: number
  buildDuration: number
}

export interface Rebate {
  ware?: string | null
  wareGroup?: string | null
  value: number
}

export interface Predecessor {
  ref: string
  type: 'project' | 'group'
  any: boolean
}

export interface TerraformingData {
  stats: TerraformingStat[]
  projectGroups: TerraformingProjectGroup[]
  projects: TerraformingProject[]
  clusters: TerraformingCluster[]
}

export interface TerraformingState {
  stats: Record<string, number>
  completedProjects: Set<string>
}

export interface TaskNode {
  id: string
  name: string
  group: string
  available: boolean
  blockedReason?: string
  effects: string
  predecessors: Predecessor[]
  children: TaskNode[]
  groupIndex?: number
}

export interface TaskTree {
  roots: TaskNode[]
  blocked: TaskNode[]
  groups: Map<string, TaskNode[]>
  groupOrder: string[]
  projectMap: Map<string, TerraformingProject>
  groupNames: Map<string, string>
}

function fmtEffect(e: StatEffect): string {
  if (e.value !== undefined) return `${e.stat}=${e.value}`
  if (e.change === undefined) return `${e.stat}`
  const sign = e.change >= 0 ? '+' : ''
  let s = `${sign}${e.change} ${e.stat}`
  if (e.min !== undefined) s += ` (min: ${e.min})`
  if (e.max !== undefined) s += ` (max: ${e.max})`
  return s
}

const GROUP_EMOJI: Record<string, string> = {
  power: '⚡',
  industry: '🏭',
  cleanup: '☢️',
  water: '💧',
  atmosphere: '🫧',
  biosphere: '🌱',
  food_staple: '🌾',
  food_luxury: '🍷',
  housing: '🏠',
  amenities: '🎪',
  training: '🎖️',
  economy: '💰',
  xenon: '👾',
  events: '⚡',
  special: '🔧',
}

function groupLabel(group: string, groupNames: Map<string, string>, i18nMap?: Record<string, string>): string {
  const emoji = GROUP_EMOJI[group] || ''
  const nameId = groupNames.get(group) || group
  const name = i18nMap ? (i18nMap[nameId] || nameId) : nameId
  return emoji ? `${emoji} ${name}` : name
}

export function loadTerraformingData(version: string): TerraformingData {
  const modules = import.meta.glob('/src/assets/x4_game_data/*/data/terraforming.json', { eager: true })
  const key = Object.keys(modules).find(k => k.includes(version))
  if (!key) throw new Error(`Version ${version} terraforming data not found`)
  return (modules[key] as { default: TerraformingData }).default
}

export function resolveAvailableTasks(
  cluster: TerraformingCluster,
  state: TerraformingState,
  data: TerraformingData,
): TaskTree {
  const projectMap = new Map<string, TerraformingProject>()
  const groupNames = new Map<string, string>()

  for (const pg of data.projectGroups) {
    groupNames.set(pg.id, pg.nameId || pg.name || pg.id)
  }

  // Filter projects in this cluster
  const clusterProjectIds = new Set(cluster.projectIds)
  const clusterProjects: TerraformingProject[] = []
  for (const p of data.projects) {
    projectMap.set(p.id, p)
    if (clusterProjectIds.has(p.id)) {
      clusterProjects.push(p)
    }
  }

  // Build dependency graph
  const blocks = new Map<string, TaskNode>()
  for (const p of clusterProjects) {
    const node = evaluateProject(p, state, projectMap)
    blocks.set(p.id, node)
  }

  // Build tree: connect children
  const roots: TaskNode[] = []
  const blocked: TaskNode[] = []
  const allChildren = new Set<string>()

  for (const [id, node] of blocks) {
    if (node.predecessors.length === 0) {
      if (!allChildren.has(id)) {
        if (node.available) {
          roots.push(node)
        } else {
          blocked.push(node)
        }
      }
    }
  }

  // Wire up parent-child
  for (const [id, node] of blocks) {
    for (const pred of node.predecessors) {
      if (pred.type === 'project') {
        const parent = blocks.get(pred.ref)
        if (parent && parent.id !== id) {
          parent.children.push(node)
          allChildren.add(id)
        }
      }
    }
  }

  // Collect blocked nodes not already in tree
  for (const [id, node] of blocks) {
    if (allChildren.has(id)) continue
    // Check if it's already a root
    const isRoot = roots.some(r => r.id === id)
    if (isRoot) continue
    if (!node.available) {
      blocked.push(node)
    }
  }

  // Collect by group
  const groups = new Map<string, TaskNode[]>()
  for (const node of blocks.values()) {
    const groupList = groups.get(node.group) || []
    groupList.push(node)
    groups.set(node.group, groupList)
  }

  return {
    roots,
    blocked,
    groups,
    groupOrder: data.projectGroups.map(g => g.id),
    projectMap,
    groupNames,
  }
}

function evaluateProject(
  project: TerraformingProject,
  state: TerraformingState,
  projectMap: Map<string, TerraformingProject>,
): TaskNode {
  const name = project.name || project.nameId
  const effectsStr = project.effects.map(fmtEffect).join(', ')
  const blockedReasons: string[] = []

  // Check stat conditions
  for (const c of project.conditions) {
    const currentVal = state.stats[c.stat]
    if (currentVal === undefined) continue
    if (c.min !== undefined && currentVal < c.min) {
      blockedReasons.push(`${c.stat} >= ${c.min} (current: ${currentVal})`)
    }
    if (c.max !== undefined && currentVal > c.max) {
      blockedReasons.push(`${c.stat} <= ${c.max} (current: ${currentVal})`)
    }
  }

  // Check predecessors (only project-type are blocking; group-type are informational)
  const unmetProjectPreds: Predecessor[] = []
  for (const pred of project.predecessors) {
    if (pred.type === 'project') {
      if (!state.completedProjects.has(pred.ref)) {
        unmetProjectPreds.push(pred)
      }
    }
    // group-type predecessors: shown in dependency label, but never block
  }

  if (unmetProjectPreds.length > 0) {
    const refs = unmetProjectPreds.map(p => {
      const pp = projectMap.get(p.ref)
      return pp ? (pp.name || pp.nameId) : p.ref
    })
    blockedReasons.push(`depends: ${refs.join(' | ')}`)
  }

  return {
    id: project.id,
    name,
    group: project.group,
    available: blockedReasons.length === 0,
    blockedReason: blockedReasons.length > 0 ? blockedReasons.join('; ') : undefined,
    effects: effectsStr,
    predecessors: project.predecessors,
    children: [],
  }
}

export function printTaskTree(tree: TaskTree, i18nMap?: Record<string, string>): string {
  const lines: string[] = []

  // Use groupOrder from data to preserve logical ordering
  const groupOrder = tree.groupOrder.filter(g => tree.groups.has(g))
  // Append any groups not in the order list
  for (const g of tree.groups.keys()) {
    if (!groupOrder.includes(g)) groupOrder.push(g)
  }

  let groupIdx = 0
  for (const group of groupOrder) {
    const nodes = tree.groups.get(group)
    if (!nodes) continue

    const label = groupLabel(group, tree.groupNames, i18nMap)
    lines.push(label)

    const sorted = sortNodes(nodes)

    for (let i = 0; i < sorted.length; i++) {
      const node = sorted[i]!
      const isLast = i === sorted.length - 1
      const prefix = isLast ? '└──' : '├──'
      const status = node.available ? '' : ' [BLOCKED]'
      const effects = node.effects ? `  (${node.effects})` : ''
      const repeat = getRepeatLabel(node.id, tree.projectMap)
      const deps = getDependencyLabel(node, tree.projectMap, i18nMap)
      const displayName = i18nMap
        ? (i18nMap[tree.projectMap.get(node.id)?.nameId || ''] || node.name)
        : node.name
      lines.push(`  ${prefix} ${displayName}${effects}${repeat}${status}`)
      if (deps) {
        lines.push(`  ${isLast ? '    ' : '│   '}  ${deps}`)
      }
      if (!node.available && node.blockedReason) {
        const reasonLines = node.blockedReason.split('; ')
        for (const r of reasonLines) {
          const translated = translateBlockedReason(r, tree.projectMap, tree.groupNames, i18nMap)
          lines.push(`  ${isLast ? '    ' : '│   '}  └─ ⛔ ${translated}`)
        }
      }
    }

    groupIdx++
    if (groupIdx < groupOrder.length) lines.push('')
  }

  return lines.join('\n')
}

function sortNodes(nodes: TaskNode[]): TaskNode[] {
  return [...nodes].sort((a, b) => {
    if (a.available !== b.available) return a.available ? -1 : 1
    return a.name.localeCompare(b.name)
  })
}

export function resolveTerraformingText(
  textId: string,
  data: TerraformingData,
  i18nMap: Record<string, string>,
): string {
  // {page,id} reference → direct i18n lookup
  if (textId.startsWith('{') && textId.endsWith('}')) {
    return i18nMap[textId] || textId
  }

  // terraforming.stat.X.name → resolve stat name
  const statMatch = textId.match(/^terraforming\.stat\.(\w+)\.name$/)
  if (statMatch) {
    const statId = statMatch[1]!
    const stat = data.stats.find(s => s.id === statId)
    const i18nKey = stat?.nameId
    if (i18nKey && i18nMap[i18nKey]) return i18nMap[i18nKey]!
    return stat?.name || statId
  }

  // terraforming.project.Y.name → resolve project name
  const projMatch = textId.match(/^terraforming\.project\.(\w+)\.name$/)
  if (projMatch) {
    const projId = projMatch[1]!
    const proj = data.projects.find(p => p.id === projId)
    const i18nKey = proj?.nameId
    if (i18nKey && i18nMap[i18nKey]) return i18nMap[i18nKey]!
    return proj?.name || projId
  }

  return textId
}

export function resolveWithReplaces(
  text: string,
  replaces: Array<{ from: string; to: string }> | undefined,
  data: TerraformingData,
  i18nMap: Record<string, string>,
): string {
  let result = text
  if (replaces) {
    for (const r of replaces) {
      const resolvedTo = resolveTerraformingText(r.to, data, i18nMap)
      result = result.replace(r.from, resolvedTo)
    }
  }
  return result
}

export function printObjectives(
  cluster: TerraformingCluster,
  data: TerraformingData,
  i18nMap: Record<string, string>,
): string {
  const lines: string[] = []
  const objs = cluster.objectives
  if (!objs || objs.length === 0) {
    lines.push('(无任务目标)')
    return lines.join('\n')
  }

  lines.push('任务目标:')
  for (const obj of objs) {
    let text = resolveTerraformingText(obj.textId, data, i18nMap)
    text = resolveWithReplaces(text, obj.textReplaces, data, i18nMap)

    const actionLabel = ACTION_LABELS[obj.action] || obj.action
    const step = String(obj.step).padStart(2, ' ')
    lines.push(`  ${step}. [${actionLabel}] ${text}`)
  }
  return lines.join('\n')
}

const ACTION_LABELS: Record<string, string> = {
  'objective.relocate': '迁移总部',
  'objective.neutralize': '消除威胁',
  'objective.build_project': '建设改造项目',
  'objective.build_housing': '建设住宅',
  'objective.build_module': '建设空间站模块',
  'objective.destroy': '摧毁目标',
  'objective.custom': '自定义目标',
}

function getRepeatLabel(projectId: string, projectMap: Map<string, TerraformingProject>): string {
  const proj = projectMap.get(projectId)
  if (!proj) return ''
  if (proj.repeatCooldown === null) return ' [一次性]'
  if (proj.repeatCooldown === 0) return ' [可重复]'
  return ` [冷却: ${proj.repeatCooldown}s]`
}

function getDependencyLabel(
  node: TaskNode,
  projectMap: Map<string, TerraformingProject>,
  i18nMap?: Record<string, string>,
): string {
  if (node.predecessors.length === 0) return ''
  const labels = node.predecessors.map(p => {
    if (p.type === 'group') return `[组: ${resolveGroupName(p.ref, i18nMap)}]`
    const pp = projectMap.get(p.ref)
    const raw = pp ? (pp.name || pp.nameId) : p.ref
    if (i18nMap && pp?.nameId) return i18nMap[pp.nameId] || raw
    return raw
  })
  const prefix = node.predecessors[0]!.any ? '⟸ 任一: ' : '⟸ '
  return prefix + labels.join(' | ')
}

function translateBlockedReason(
  reason: string,
  projectMap: Map<string, TerraformingProject>,
  _groupNames: Map<string, string>,
  i18nMap?: Record<string, string>,
): string {
  // "depends: Fertilise Soil | Genetically Modify Toxic Fruit"
  if (reason.startsWith('depends: ')) {
    const rest = reason.slice('depends: '.length)
    const parts = rest.split(' | ')
    const translated = parts.map(p => {
      if (p.startsWith('group: ')) {
        const gName = p.slice('group: '.length)
        return `[组: ${resolveGroupName(gName, i18nMap)}]`
      }
      // Try to find project by name
      for (const proj of projectMap.values()) {
        if ((proj.name || proj.nameId) === p) {
          if (i18nMap && proj.nameId) return i18nMap[proj.nameId] || p
          return p
        }
      }
      return p
    }).join(' | ')
    return `需要: ${translated}`
  }
  return reason
}

function resolveGroupName(groupId: string, i18nMap?: Record<string, string>): string {
  if (!i18nMap) return groupId
  // Direct i18n lookup
  if (i18nMap[groupId]) return i18nMap[groupId]
  return groupId
}
