<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="NonNegativeFloat">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="regionyields">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="boundaries">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="boundary" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="position" minOccurs="0" maxOccurs="1">
                      <xs:annotation>
                        <xs:documentation>
                          Boundary position offset
                        </xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="x" type="xs:float" />
                        <xs:attribute name="y" type="xs:float" />
                        <xs:attribute name="z" type="xs:float" />
                      </xs:complexType>
                    </xs:element>
                    <xs:choice minOccurs="0" maxOccurs="1">
                      <xs:element name="rotation">
                        <xs:annotation>
                          <xs:documentation>
                            Boundary rotation offset
                          </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:attribute name="yaw" type="xs:float" />
                          <xs:attribute name="pitch" type="xs:float" />
                          <xs:attribute name="roll" type="xs:float" />
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="quaternion">
                        <xs:annotation>
                          <xs:documentation>
                            Boundary rotation offset
                          </xs:documentation>
                        </xs:annotation>
                        <xs:complexType>
                          <xs:attribute name="qw" type="xs:float" />
                          <xs:attribute name="qx" type="xs:float" />
                          <xs:attribute name="qy" type="xs:float" />
                          <xs:attribute name="qz" type="xs:float" />
                        </xs:complexType>
                      </xs:element>
                    </xs:choice>
                    <xs:element minOccurs="1" maxOccurs="1" name="size">
                      <xs:complexType>
                        <xs:attribute name="r" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Radius for sphere, cylinder or spline tube boundaries.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="linear" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Height for cylinder boundaries.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="x" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Side length in x direction for box boundaries.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="y" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Side length in y direction for box boundaries.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="z" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Side length in z direction for box boundaries.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="splineposition">
                      <xs:annotation>
                        <xs:documentation>
                          Spline point. Coordinates are relative to the region. tx/ty/tz are the tangent direction.
                        </xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="x" type="xs:float" />
                        <xs:attribute name="y" type="xs:float" />
                        <xs:attribute name="z" type="xs:float" />
                        <xs:attribute name="tx" type="xs:float" />
                        <xs:attribute name="ty" type="xs:float" />
                        <xs:attribute name="tz" type="xs:float" />
                        <xs:attribute name="inlength" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Incoming tangent length.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="outlength" type="NonNegativeFloat">
                          <xs:annotation>
                            <xs:documentation>
                              Outgoing tangent length.
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The string for this boundary type which will become part of the full yield definition ID
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="class" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="box" />
                        <xs:enumeration value="sphere" />
                        <xs:enumeration value="cylinder" />
                        <xs:enumeration value="splinetube" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="invert" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>
                        Whether this boundary is an inverse one, "cutting a hole" into the other boundaries
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="yields">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="yield" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ware" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>
                              The ware ID which will become part of the full yield definition ID
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="yield" type="xs:positiveInteger" use="required">
                          <xs:annotation>
                            <xs:documentation>
                              The total amount of yield in this area
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="respawndelay" type="xs:float">
                          <xs:annotation>
                            <xs:documentation>
                              The time after it was depleted (in minutes) before this resource area is respawned at a random location. Defaults to 0. Set to -1 to prevent respawning
                            </xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The string for this yield amount which will become part of the full yield definition ID
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="tag" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>
                        An optional compatibility tag - needs to be set if it should appear in regions that have a yield tag list defined for this ware.
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="scaneffect" type="xs:string" use="optional">
                    <xs:annotation>
                      <xs:documentation>
                        The scan result effect definition, see libraries/effects.xml
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="scaneffectamount" type="xs:nonNegativeInteger" use="optional">
                    <xs:annotation>
                      <xs:documentation>
                        The scan result effect amount, defaults to 1
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="scaneffectintensity" type="xs:float">
                    <xs:annotation>
                      <xs:documentation>
                        The scan result effect intensity (opacity, volume, etc.), defaults to 1.0
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="gatherspeeds">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="gatherspeed" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The string for this gather speed type which will become part of the full yield definition ID
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="factor">
                    <xs:annotation>
                      <xs:documentation>
                        An optional factor to the yield contained in each object (for solid resources) or gather speed (for liquid resources). Defaults to 1
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:float">
                        <xs:minExclusive value="0" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="rating" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The star rating of this resource area, multiplied by 3. Maximum value of 15 is 5 stars.
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0" />
                        <xs:maxInclusive value="15" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="definitions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="definition" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>
                    A region object group, to be referenced in region_definitions.xml
                  </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="boundary">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="position" minOccurs="0" maxOccurs="1">
                            <xs:annotation>
                              <xs:documentation>
                                Boundary position offset
                              </xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:attribute name="x" type="xs:float" />
                              <xs:attribute name="y" type="xs:float" />
                              <xs:attribute name="z" type="xs:float" />
                            </xs:complexType>
                          </xs:element>
                          <xs:choice minOccurs="0" maxOccurs="1">
                            <xs:element name="rotation">
                              <xs:annotation>
                                <xs:documentation>
                                  Boundary rotation offset
                                </xs:documentation>
                              </xs:annotation>
                              <xs:complexType>
                                <xs:attribute name="yaw" type="xs:float" />
                                <xs:attribute name="pitch" type="xs:float" />
                                <xs:attribute name="roll" type="xs:float" />
                              </xs:complexType>
                            </xs:element>
                            <xs:element name="quaternion">
                              <xs:annotation>
                                <xs:documentation>
                                  Boundary rotation offset
                                </xs:documentation>
                              </xs:annotation>
                              <xs:complexType>
                                <xs:attribute name="qw" type="xs:float" />
                                <xs:attribute name="qx" type="xs:float" />
                                <xs:attribute name="qy" type="xs:float" />
                                <xs:attribute name="qz" type="xs:float" />
                              </xs:complexType>
                            </xs:element>
                          </xs:choice>
                          <xs:element minOccurs="1" maxOccurs="1" name="size">
                            <xs:complexType>
                              <xs:attribute name="r">
                                <xs:annotation>
                                  <xs:documentation>
                                    Radius for sphere, cylinder or spline tube boundaries.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="linear">
                                <xs:annotation>
                                  <xs:documentation>
                                    Height for cylinder boundaries.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="x">
                                <xs:annotation>
                                  <xs:documentation>
                                    Side length in x direction for box boundaries.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="y">
                                <xs:annotation>
                                  <xs:documentation>
                                    Side length in y direction for box boundaries.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="z">
                                <xs:annotation>
                                  <xs:documentation>
                                    Side length in z direction for box boundaries.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="splineposition">
                            <xs:annotation>
                              <xs:documentation>
                                Spline point. Coordinates are relative to the region. tx/ty/tz are the tangent direction.
                              </xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:attribute name="x" type="xs:float" />
                              <xs:attribute name="y" type="xs:float" />
                              <xs:attribute name="z" type="xs:float" />
                              <xs:attribute name="tx" type="xs:float" />
                              <xs:attribute name="ty" type="xs:float" />
                              <xs:attribute name="tz" type="xs:float" />
                              <xs:attribute name="inlength">
                                <xs:annotation>
                                  <xs:documentation>
                                    Incoming tangent length.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="outlength">
                                <xs:annotation>
                                  <xs:documentation>
                                    Outgoing tangent length.
                                  </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                  <xs:restriction base="xs:float">
                                    <xs:minExclusive value="0" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="class" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                              <xs:enumeration value="box" />
                              <xs:enumeration value="sphere" />
                              <xs:enumeration value="cylinder" />
                              <xs:enumeration value="splinetube" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The ID of this region yield area definition
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="ware" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The ware ID of the contained resource
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="ore" />
                        <xs:enumeration value="nividium" />
                        <xs:enumeration value="silicon" />
                        <xs:enumeration value="ice" />
                        <xs:enumeration value="hydrogen" />
                        <xs:enumeration value="helium" />
                        <xs:enumeration value="methane" />
                        <xs:enumeration value="rawscrap" />
                        <xs:enumeration value="rawkhaakscrap" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="yield" type="xs:positiveInteger" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The total amount of yield in this area
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="factor">
                    <xs:annotation>
                      <xs:documentation>
                        An optional factor to the yield contained in each object (for solid resources) or gather speed (for liquid resources). Defaults to 1
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:float">
                        <xs:minExclusive value="0" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="respawndelay" type="xs:float">
                    <xs:annotation>
                      <xs:documentation>
                        The time after it was depleted (in minutes) before this resource area is respawned at a random location. Defaults to 0. Set to -1 to prevent respawning
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="rating" use="required">
                    <xs:annotation>
                      <xs:documentation>
                        The star rating of this resource area, multiplied by 3. Maximum value of 15 is 5 stars.
                      </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0" />
                        <xs:maxInclusive value="15" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="tag" type="xs:string">
                    <xs:annotation>
                      <xs:documentation>
                        An optional compatibility tag - needs to be set if it should appear in regions that have a yield tag list defined for this ware.
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="randompitch" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>
                        Whether the pitch angle should be randomized on spawn
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="randomyaw" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>
                        Whether the yaw angle should be randomized on spawn
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="randomroll" type="xs:boolean">
                    <xs:annotation>
                      <xs:documentation>
                        Whether the roll angle should be randomized on spawn
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="scaneffect" type="xs:string" use="optional">
                    <xs:annotation>
                      <xs:documentation>
                        The scan result effect definition, see libraries/effects.xml
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="scaneffectamount" type="xs:nonNegativeInteger" use="optional">
                    <xs:annotation>
                      <xs:documentation>
                        The scan result effect amount, defaults to 1
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="scaneffectintensity" type="xs:float">
                    <xs:annotation>
                      <xs:documentation>
                        The scan result effect intensity (opacity, volume, etc.), defaults to 1.0
                      </xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
