import { test } from '../../test-setup'
import { expect, type Page } from '@playwright/test'
import { setupLogicFlow } from './helpers/setupLogicFlow'
import { dragWareToTarget, expectDragIdle, getGroupIdForWare } from './helpers/dragLogicFlow'

const node = (page: Page, ware: string) => page.locator(`.flow-node[data-ware-id="${ware}"]`)
async function hullGroup(page: Page) {
  await dragWareToTarget(page, 'hullparts')
  return getGroupIdForWare(page, 'hullparts')
}
async function editTitle(page: Page, value: string) {
  await page.locator('.production-group h3').click()
  const input = page.locator('.production-group input:not([type="checkbox"])')
  await input.fill(value)
  return input
}
async function groupName(page: Page, id: string) {
  return page.evaluate(id => (window as any).logicFlowStore.groups.find((group: any) => group.id === id).name, id)
}
async function highlightedWares(page: Page) {
  return page.locator('.flow-node.highlighted-node').evaluateAll(nodes => nodes.map(node => node.getAttribute('data-ware-id')).sort())
}
async function release(page: Page) {
  await page.mouse.up()
  await expectDragIdle(page)
}

// Fixed 8.0 weapon-component dependencies, not generated by the highlight implementation.
const weaponChain = ['graphene', 'helium', 'hullparts', 'methane', 'ore', 'plasmaconductors', 'refinedmetals', 'superfluidcoolant', 'weaponcomponents']
const oreChain = ['hullparts', 'ore', 'refinedmetals', 'weaponcomponents']

test.describe('Logic Flow New Features', () => {
  test.beforeEach(async ({ page }) => {
    page.on('pageerror', (err) => {
      console.error(`Page Error: ${err.message}`)
    })
    await setupLogicFlow(page, 'clean')
    await page.addStyleTag({ content: '*, *::before, *::after { transition: none !important; animation: none !important; }' })
  })

  test('Test 1: Title Edit Interaction - Click to Edit', async ({ page }) => {
    await hullGroup(page)
    await page.locator('.production-group h3').click()
    const input = page.locator('.production-group input:not([type="checkbox"])')
    await expect(input).toBeVisible()
    await expect(input).toBeFocused()
    await expect(page.locator('.production-group button.text-green-400')).toBeVisible()
  })
  test('Test 2: Title Confirm Edit', async ({ page }) => {
    const id = await hullGroup(page)
    await (await editTitle(page, '我的产线')).press('Enter')
    await expect(page.locator('.production-group h3')).toHaveText('我的产线')
    await expect.poll(() => groupName(page, id)).toBe('我的产线')
  })
  test('Test 3: Title Cancel Edit - Blur', async ({ page }) => {
    const id = await hullGroup(page)
    await expect(page.locator('.production-group h3')).toHaveText('船体部件')
    await editTitle(page, 'Modified Title')
    await page.getByTestId('top-view-btn-flow').click()
    await expect(page.locator('.production-group h3')).toHaveText('船体部件')
    await expect.poll(() => groupName(page, id)).toBe('')
  })
  test('Test 4: Empty Title Reversion', async ({ page }) => {
    const id = await hullGroup(page)
    await (await editTitle(page, '自定义')).press('Enter')
    await expect(page.locator('.production-group h3')).toHaveText('自定义')
    await (await editTitle(page, '')).press('Enter')
    await expect(page.locator('.production-group h3')).toHaveText('船体部件')
    await expect.poll(() => groupName(page, id)).toBe('')
  })
  test('Test 5: Custom Title Not Auto Updated', async ({ page }) => {
    const groupId = await hullGroup(page)
    await (await editTitle(page, '我的产线')).press('Enter')
    await dragWareToTarget(page, 'weaponcomponents', { groupId }, { expectedStatus: 'locked' })
    await expect(node(page, 'weaponcomponents')).toBeVisible()
    await expect(page.locator('.production-group h3')).toHaveText('我的产线')
    await expect.poll(() => groupName(page, groupId)).toBe('我的产线')
  })
  for (const scenario of [
    { title: 'Test 6: Upstream Trace to T0', ware: 'weaponcomponents', expected: weaponChain },
    { title: 'Test 7: Downstream Trace to T3', ware: 'ore', expected: oreChain },
    { title: 'Test 8: Middle Tier Bidirectional Trace', ware: 'refinedmetals', expected: oreChain },
  ]) {
    test(scenario.title, async ({ page }) => {
      await dragWareToTarget(page, 'weaponcomponents')
      await node(page, scenario.ware).hover()
      await expect.poll(() => highlightedWares(page)).toEqual(scenario.expected)
      await expect(node(page, 'energycells')).not.toHaveClass(/highlighted-node/)
    })
  }
  test('Test 9: Leave Node Clears Highlight', async ({ page }) => {
    await dragWareToTarget(page, 'weaponcomponents')
    await node(page, 'ore').hover()
    await expect.poll(() => highlightedWares(page)).toEqual(oreChain)
    await page.mouse.move(0, 0, { steps: 5 })
    await expect.poll(() => highlightedWares(page)).toEqual([])
    await expect(page.locator('.highlighted-connection')).toHaveCount(0)
  })
  test('Test 9.1: Isolated Node Highlight', async ({ page }) => {
    await dragWareToTarget(page, 'weaponcomponents')
    const hull = node(page, 'hullparts')
    await hull.hover()
    await hull.locator('button[title*="隔离"], button[title*="Isolate"]').click()
    await expect(hull).toContainText('EXT')
    await page.mouse.move(0, 0)
    await hull.hover()
    await expect.poll(() => highlightedWares(page)).toEqual(['hullparts', 'weaponcomponents'])
    await expect(node(page, 'ore')).toHaveCount(0)
  })
  test('Test 15: Button Position Verification', async ({ page }) => {
    const language = await page.getByTestId('language-select').boundingBox()
    const flow = await page.getByTestId('top-view-btn-flow').boundingBox()
    if (!language || !flow) throw new Error('Visible toolbar controls required')
    expect(flow.x + flow.width).toBeLessThanOrEqual(language.x + 5)
  })
  test('Test 16: View Switch Functionality', async ({ page }) => {
    await page.getByTestId('top-view-btn-blueprint-production').click()
    await expect(page.locator('.candidate-zone')).toBeHidden()
    await page.getByTestId('top-view-btn-flow').click()
    await expect(page.locator('.candidate-zone')).toBeVisible()
    await expect(page.getByTestId('top-view-btn-flow')).toHaveClass(/bg-purple-600/)
  })
  test('Test 17: Compact Mode Shows Custom Title', async ({ page }) => {
    const groupId = await hullGroup(page)
    await (await editTitle(page, '我的产线')).press('Enter')
    const { targetLocator } = await dragWareToTarget(page, 'weaponcomponents', { groupId }, { drop: false, expectedStatus: 'locked' })
    await expect(targetLocator.locator('span.truncate').first()).toHaveText('我的产线')
    await release(page)
    await expect(node(page, 'weaponcomponents')).toBeVisible()
  })
  test('Test 18: T0 Resources Fully Displayed', async ({ page }) => {
    await dragWareToTarget(page, 'weaponcomponents')
    const groupId = await getGroupIdForWare(page, 'weaponcomponents')
    const { targetLocator } = await dragWareToTarget(page, 'hullparts', { groupId }, { drop: false, expectedStatus: 'auto' })
    const resources = targetLocator.locator('.flex.items-center [data-ware-id]')
    await expect.poll(() => resources.evaluateAll(nodes => nodes.map(node => node.getAttribute('data-ware-id')).sort())).toEqual(['helium', 'methane', 'ore'])
    await release(page)
    await expect.poll(() => page.evaluate(id => (window as any).logicFlowStore.groups.find((group: any) => group.id === id).nodes.find((node: any) => node.wareId === 'hullparts').source, groupId)).toBe('manual')
  })
  test('Test 19: Preview Menu Title Abbreviation', async ({ page }) => {
    const groupId = await hullGroup(page)
    const title = '这是一个非常长的自定义产线标题'.repeat(5)
    await (await editTitle(page, title)).press('Enter')
    const { targetLocator } = await dragWareToTarget(page, 'weaponcomponents', { groupId }, { drop: false, expectedStatus: 'locked' })
    const label = targetLocator.locator('span.truncate').first()
    await expect(label).toHaveText(title)
    await expect(label).toHaveCSS('text-overflow', 'ellipsis')
    expect(await label.evaluate(el => el.scrollWidth > el.clientWidth)).toBe(true)
    await release(page)
    await expect.poll(() => groupName(page, groupId)).toBe(title)
  })
  test('Test 10: Edit Mode UI Consistency', async ({ page }) => {
    await hullGroup(page)
    const input = await editTitle(page, '编辑')
    await expect(input).toHaveClass(/bg-slate-700/)
    await expect(input).toHaveClass(/border/)
    await expect(page.locator('.production-group button.text-green-400')).toBeVisible()
  })
  test('Test 11: Edit Mode Height Stability', async ({ page }) => {
    await hullGroup(page)
    const header = page.locator('.production-group > div').first()
    const before = await header.boundingBox()
    await editTitle(page, '编辑')
    const after = await header.boundingBox()
    if (!before || !after) throw new Error('Group header must remain visible')
    expect(Math.abs(after.height - before.height)).toBeLessThan(5)
  })
  test('Test 12: Container Highlight Style', async ({ page }) => {
    await dragWareToTarget(page, 'weaponcomponents')
    const ore = node(page, 'ore')
    await ore.hover()
    await expect(ore).toHaveClass(/highlighted-node/)
    await expect(ore).toHaveCSS('border-color', 'rgba(59, 130, 246, 0.6)')
    await expect(ore).toHaveCSS('background-color', 'rgba(59, 130, 246, 0.15)')
  })
  test('Test 13: Connection Highlight Style', async ({ page }) => {
    await dragWareToTarget(page, 'weaponcomponents')
    await node(page, 'ore').hover()
    const paths = page.locator('.highlighted-connection')
    await expect(paths).toHaveCount(3)
    for (const path of await paths.all()) {
      await expect(path).toHaveAttribute('stroke', 'rgba(59,130,246,0.8)')
      await expect(path).toHaveAttribute('stroke-width', '2.5')
      await expect(path).toHaveAttribute('marker-end', 'url(#arrowhead-highlighted)')
    }
  })
})
