/**
 * Mock Data Generator for X4 Station Calculator
 * 
 * This module generates mock data based on the existing UI component logic
 * to create realistic test data for development and testing purposes.
 */

// Import necessary types from the application
import type { 
  SavedModule, 
  X4Module, 
  X4Ware, 
  WareFlow, 
  StationSettings,
  WorkforceItem
} from '../src/types/x4';

// Import ConstructionBreakdown separately since it's defined in productionCalculator
import type { ConstructionBreakdown } from '../src/store/logic/productionCalculator';

// Import the logic functions from the application
import { calculateAutoFill } from '../src/store/logic/moduleDiffCalculator';
import { analyzeWareFlow } from '../src/store/logic/analyzeWareFlow';
import { calculateWorkforceBreakdown } from '../src/store/logic/workforceCalculator';
import { calculateConstructionBreakdown } from '../src/store/logic/productionCalculator';



// Interface definitions for the mock data generator
export interface MockModuleConfig {
  module: string;
  count: number;
}

export interface MockGroupConfig {
  groupId: string;
  modules: MockModuleConfig[];
}

export interface GeneratedMockData {
  planned: SavedModule[];
  industryModules: SavedModule[];
  industryModulesWithWorker: SavedModule[];
  supplyModules: SavedModule[];
  supplyModulesWithWorker: SavedModule[];
  wareFlows: WareFlow[];
  stationWorkforce: {
    needed: {
      total: number;
      breakdown: WorkforceItem[];
    };
    capacity: {
      total: number;
      breakdown: WorkforceItem[];
    };
  };
  stationConstructions: ConstructionBreakdown;
}

/**
 * Main function to generate mock data based on configuration
 */
export async function generateMockData(): Promise<GeneratedMockData[]> {
  try {
    // Read configuration from the config file
    const config = await readConfig();
    const mockGroups = config.mock_modules || [];
    
    const results: GeneratedMockData[] = [];
    
    for (let i = 0; i < mockGroups.length; i++) {
      const group = mockGroups[i];
      const groupId = `group_${i + 1}`;
      
      const groupResult = await generateMockDataForGroup(groupId, group);
      results.push(groupResult);
    }
    
    return results;
  } catch (error) {
    console.error('Error generating mock data:', error);
    throw error;
  }
}

/**
 * Generate industry modules based on configuration
 */
async function generateIndustryModules(
  modules: MockModuleConfig[], 
  modulesMap: Record<string, X4Module>, 
  waresMap: Record<string, X4Ware>
): Promise<{ planned: SavedModule[], autoGenerated: SavedModule[] }> {
  // Convert MockModuleConfig to SavedModule format for planned modules
  const plannedModules: SavedModule[] = [];
  for (const moduleConfig of modules) {
    // Find the actual module by name
    const foundModule = Object.values(modulesMap).find(
      (mod: X4Module) => mod.name.toLowerCase().includes(moduleConfig.module.toLowerCase())
    ) as X4Module | undefined;
    
    if (foundModule) {
      plannedModules.push({
        id: foundModule.id,
        count: moduleConfig.count
      });
    }
  }
  
  // Generate auto-fill modules using the same logic as in moduleDiffCalculator
  const { autoIndustry } = calculateAutoFill(
    plannedModules,
    'teladi', // Default race, could be configurable
    true, // globalWorkforceBonus
    true, // supplyWorkforceBonus
    modulesMap,
    waresMap,
    [] // lockedWares
  );
  
  return {
    planned: plannedModules,
    autoGenerated: autoIndustry
  };
}

/**
 * Generate supply modules based on configuration
 */
async function generateSupplyModules(
  plannedModules: SavedModule[],
  autoIndustryModules: SavedModule[],
  modulesMap: Record<string, X4Module>, 
  waresMap: Record<string, X4Ware>
): Promise<SavedModule[]> {
  // Generate auto-fill supply modules using the same logic as in moduleDiffCalculator
  const { autoSupply } = calculateAutoFill(
    [...plannedModules, ...autoIndustryModules],
    'teladi', // Default race, could be configurable
    true, // globalWorkforceBonus
    true, // supplyWorkforceBonus
    modulesMap,
    waresMap,
    [] // lockedWares
  );
  
  return autoSupply;
}

/**
 * Generate ware flows based on modules
 */
async function generateWareFlows(
  industryModules: SavedModule[],
  modulesMap: Record<string, X4Module>,
  waresMap: Record<string, X4Ware>,
  settings: StationSettings
): Promise<WareFlow[]> {
  return analyzeWareFlow(
    industryModules,
    [], // plannedWareIds - could be configurable
    modulesMap,
    waresMap,
    {}, // medicalConsumptionMap
    settings,
    1000, // actualWorkforce - mock value
    1.0, // saturation - mock value
    1.0, // resourceBufferHours
    1.0 // productBufferHours
  );
}

/**
 * Generate workforce data based on modules
 */
async function generateWorkforce(
  industryModules: SavedModule[],
  modulesMap: Record<string, X4Module>,
  settings: StationSettings
): Promise<{
  needed: {
    total: number;
    breakdown: WorkforceItem[];
  };
  capacity: {
    total: number;
    breakdown: WorkforceItem[];
  };
}> {
  const workforceBreakdown = calculateWorkforceBreakdown(
    industryModules,
    modulesMap,
    settings
  );
  
  return {
    needed: {
      total: workforceBreakdown.needed.total,
      breakdown: workforceBreakdown.needed.list
    },
    capacity: {
      total: workforceBreakdown.capacity.total,
      breakdown: workforceBreakdown.capacity.list
    }
  };
}

/**
 * Generate construction data based on modules
 */
async function generateConstruction(
  industryModules: SavedModule[],
  modulesMap: Record<string, X4Module>,
  waresMap: Record<string, X4Ware>
): Promise<ConstructionBreakdown> {
  return calculateConstructionBreakdown(
    industryModules,
    modulesMap,
    waresMap
  );
}

/**
 * Generate mock data for a specific group
 */
async function generateMockDataForGroup(groupId: string, modulesInput: any[]): Promise<GeneratedMockData> {
  // Convert the input to the expected format if needed
  let modules: MockModuleConfig[] = [];
  
  // Check if modulesInput is an array of objects like [{module, count}, ...]
  if (Array.isArray(modulesInput) && modulesInput.length > 0) {
    // It's already in the correct format
    modules = modulesInput as MockModuleConfig[];
  } else if (typeof modulesInput === 'object' && modulesInput !== null) {
    // It's in the converted format like {module1: count1, module2: count2, ...}
    // Convert it back to the array format
    modules = Object.entries(modulesInput).map(([module, count]) => ({
      module,
      count: count as number
    }));
  }
  
  // First, we need to load the actual game data
  const gameData = await loadGameData();
  const { modules: modulesMap, wares: waresMap } = gameData;
  
  // Generate industry modules (First calculation)
  const { planned, autoGenerated } = await generateIndustryModules(modules, modulesMap, waresMap);
  let industryModules = [...planned, ...autoGenerated];
  let industryModulesWithWorker = [...planned, ...autoGenerated]; // Same for mock data
  
  // Generate supply modules (Second calculation)
  const autoSupply = await generateSupplyModules(planned, autoGenerated, modulesMap, waresMap);
  let supplyModules = [...autoSupply];
  let supplyModulesWithWorker = [...autoSupply]; // Same for mock data
  
  // Generate ware flows (Third calculation) with updated modules
  const allIndustryModules = [...planned, ...autoGenerated];
  const wareFlows = await generateWareFlows(
    allIndustryModules,
    modulesMap,
    waresMap,
    {
      sunlight: 100,
      useHQ: false,
      manualWorkforce: 0,
      workforcePercent: 100,
      workforceAuto: true,
      considerWorkforceForAutoFill: true,
      supplyWorkforceBonus: true,
      buyMultiplier: 1.0,
      sellMultiplier: 1.0,
      minersEnabled: false,
      internalSupply: false,
      racePreference: 'teladi',
      resourceBufferHours: 1.0,
      productBufferHours: 1.0
    }
  );
  
  // Generate workforce data based on updated modules
  const stationWorkforce = await generateWorkforce(
    allIndustryModules,
    modulesMap,
    {
      sunlight: 100,
      useHQ: false,
      manualWorkforce: 0,
      workforcePercent: 100,
      workforceAuto: true,
      considerWorkforceForAutoFill: true,
      supplyWorkforceBonus: true,
      buyMultiplier: 1.0,
      sellMultiplier: 1.0,
      minersEnabled: false,
      internalSupply: false,
      racePreference: 'teladi',
      resourceBufferHours: 1.0,
      productBufferHours: 1.0
    }
  );
  
  // Generate construction data based on updated modules
  const stationConstructions = await generateConstruction(
    allIndustryModules,
    modulesMap,
    waresMap
  );
  
  return {
    planned,
    industryModules: allIndustryModules,
    industryModulesWithWorker: allIndustryModules,
    supplyModules,
    supplyModulesWithWorker,
    wareFlows,
    stationWorkforce,
    stationConstructions
  };
}

/**
 * Load game data (modules and wares)
 */
async function loadGameData(): Promise<{ modules: Record<string, X4Module>, wares: Record<string, X4Ware> }> {
  // In Node.js environment, we need to import the raw data directly
  // since Vue composables won't work outside of component context
  try {
    // Try to import raw game data directly
    const modulesRaw = await import('../src/assets/x4_game_data/8.0-Diplomacy/data/modules.json', { assert: { type: 'json' } });
    const waresRaw = await import('../src/assets/x4_game_data/8.0-Diplomacy/data/wares.json', { assert: { type: 'json' } });
    
    // Convert arrays to maps
    const modulesMap: Record<string, X4Module> = {};
    (modulesRaw.default || modulesRaw).forEach((module: X4Module) => {
      modulesMap[module.id] = module;
    });
    
    const waresMap: Record<string, X4Ware> = {};
    (waresRaw.default || waresRaw).forEach((ware: X4Ware) => {
      waresMap[ware.id] = ware;
    });
    
    return {
      modules: modulesMap,
      wares: waresMap
    };
  } catch (error) {
    console.error('Failed to load game data directly:', error);
    throw error;
  }
}

/**
 * Read configuration from the config file
 */
async function readConfig(): Promise<any> {
  // In Node.js environment during build/dev, we need to import differently
  // For browser environment during runtime, we fetch the config
  try {
    // Try to import directly if in build environment
    const configModule = await import('../x4-station-calculator.config.json');
    return configModule.default || configModule;
  } catch {
    // Fallback to fetch if direct import fails
    try {
      const configResponse = await fetch('./x4-station-calculator.config.json');
      return await configResponse.json();
    } catch {
      // If fetch also fails, create a fallback config
      console.warn('Could not load config file, using fallback');
      return {
        mock_modules: [
          [{"module": "claytronics", "count": 6}, {"module": "hullparts", "count": 12}],
          [{"module": "claytronics", "count": 6}]
        ]
      };
    }
  }
}

/**
 * Execution entry point
 */
async function run() {
  try {
    const results = await generateMockData();
    console.log('🚀 Successfully generated mock data!');
    console.log(`📊 Generated ${results.length} mock data sets`);
    
    // Write to a file
    const fs = await import('fs');
    const path = await import('path');
    
    const outputPath = path.join(process.cwd(), 'src', 'mock', 'station_mock_data.json');
    fs.writeFileSync(outputPath, JSON.stringify(results, null, 2));
    
    console.log(`💾 Data written to ${outputPath}`);
    
    // Print summary
    results.forEach((result, index) => {
      console.log(`\n📋 Dataset ${index + 1}:`);
      console.log(`   Planned: ${result.planned.length}`);
      console.log(`   Industry Modules: ${result.industryModules.length}`);
      console.log(`   Supply Modules: ${result.supplyModules.length}`);
      console.log(`   Ware Flows: ${result.wareFlows.length}`);
      console.log(`   Workforce Needed: ${result.stationWorkforce.needed.total}`);
      console.log(`   Workforce Capacity: ${result.stationWorkforce.capacity.total}`);
      console.log(`   Construction Cost: ${result.stationConstructions.totalCost}`);
    });
  } catch (error) {
    console.error('❌ Failed to run mock data generator:', error);
    process.exit(1);
  }
}

// ESM 兼容的启动逻辑
const isMainModule = import.meta.url.startsWith('file:');
const runningAsScript = process.argv[1] && 
  (process.argv[1].endsWith('mockDataGenerator.ts') || 
   process.argv[1].endsWith('mockDataGenerator.js'));

if (isMainModule && runningAsScript) {
  run().catch(err => {
    console.error('Final Catch:', err);
    process.exit(1);
  });
}

// Export a default function for easy usage
export default generateMockData;