"""SplineTubeBoundary class - reverse engineered from X4.exe.

C++ class: U::SplineTubeBoundary
Base class: U::Boundary
Constructor: 0x14078eac0
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from .boundary import Boundary
from .composite_spline import CompositeSpline

if TYPE_CHECKING:
    from .boundary_list import BoundaryList
    from .cylinder_boundary import CylinderBoundary

# Constants from C++ DAT_*
DAT_142d800e8 = 1.0


@dataclass
class SplineControlPoint:
    """Spline control point with tangent and lengths."""
    x: float
    y: float
    z: float
    tx: float  # tangent x
    ty: float  # tangent y
    tz: float  # tangent z
    inlength: float
    outlength: float


def vec3_sub(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def vec3_dot(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def vec3_length(a: tuple[float, float, float]) -> float:
    return math.sqrt(vec3_dot(a, a))


def clamp(value: float, lower: float, upper: float) -> float:
    return max(lower, min(upper, value))


@dataclass
class SplineTubeBoundary(Boundary):
    """SplineTubeBoundary - a tube along a spline path.

    C++ class: U::SplineTubeBoundary
    Constructor: 0x14078eac0
    VTable (offset=0): 0x142bde590 (main vftable)
    VTable (offset=8): 0x142bde550 (spline subobject vftable)

    COL (Complete Object Locator):
        COL(offset=0): 0x142db98a8 -> vfptr: 0x142bde590
        COL(offset=8): 0x142db98f8 -> vfptr: 0x142bde550

    Memory layout (offsets from this pointer):
        +0x00: vptr (main)
        +0x08: radius (float) - tube radius
        +0x10: CompositeSpline<3> subobject start
            +0x10: vptr (spline)
            +0x18: spline data...
        +0x38: transform matrix (4x4 float[16])
        +0x60: sample_count (int)
        +0x68: total_length (float)
        +0x70: BoundaryList vftable
        +0x78: cylinder_boundaries array start
        +0x80: cylinder_boundaries array end
        +0x88: cylinder_boundaries array capacity
        +0x120: BoxBoundary start

    VTable slots (main, vfptr = 0x142bde590):
        +0x00 -> 0x140582d60: destructor
        +0x08 -> 0x140169370
        +0x10 -> 0x14011b510: check_intersection
        +0x18 -> 0x1403526a0
        +0x20 -> 0x1403526a0
        +0x28 -> 0x14093e440
        +0x30 -> 0x14093eaa0
        +0x38 -> 0x14093eb60: point_containment_check
        +0x40 -> 0x14093ed00
        +0x48 -> 0x14009d970: has_lateral_falloff
        +0x50 -> 0x14093ed10
        +0x58 -> 0x14093ed40: get_lateral_interval
        +0x60 -> 0x14009d970: has_radial_falloff
        +0x68 -> 0x14093ed70: get_nearest_radial_distance
        +0x70 -> 0x14093ee10: get_radial_interval
        +0x78 -> 0x14093efc0: get_volume

    Coordinate system:
        - After from_region_json(), spline control points are in WORLD coordinates
          (transform_spline_to_world() is called automatically)
        - position_x/y/z store the original boundary position (for reference/reversal)
        - All intersection methods work directly with world coordinates
        - Use transform_spline_to_local() to revert to local coordinates if needed
    """

    # Position of the boundary in world coordinates
    # Corresponds to the transform matrix at offset +0x38
    position_x: float = 0.0
    position_y: float = 0.0
    position_z: float = 0.0

    # Member data
    radius: float = 0.0  # +0x08: tube radius
    spline: list[SplineControlPoint] = field(default_factory=list)  # WORLD coordinates after transform

    # +0x10: CompositeSpline<3> subobject
    # This is the spline geometry that the tube follows
    _composite_spline: CompositeSpline = field(default_factory=CompositeSpline)

    # Legacy fields (now delegated to _composite_spline)
    # Kept for backward compatibility during transition
    sampled_points: list[tuple[float, float, float]] = field(default_factory=list)
    seg_lengths: list[float] = field(default_factory=list)
    accum: list[float] = field(default_factory=list)
    total_length: float = 0.0

    transform: list[float] = field(default_factory=lambda: [1.0] * 16)  # 4x4 matrix, identity
    _spline_is_world: bool = field(default=False, repr=False)  # Track coordinate state

    # +0x78: CylinderBoundary array (generated by FUN_14093e5c0)
    cylinder_boundaries: list['CylinderBoundary'] = field(default_factory=list)

    # +0x120: BoxBoundary for bounding box (generated by FUN_14093e5c0)
    box_min: tuple[float, float, float] | None = None
    box_max: tuple[float, float, float] | None = None

    def _ensure_sampled(self, sample_count: int = 2000) -> None:
        """Build sampled points from spline control points.

        Corresponds to FUN_14078eac0 initialization logic.
        Uses uniform parameter sampling across all segments.
        """
        if self.sampled_points:
            return

        if len(self.spline) < 2:
            return

        # Sample at uniform parameter intervals
        for i in range(sample_count + 1):
            t = i / sample_count
            point = self._sample_spline_uniform(t)
            self.sampled_points.append(point)

        # Build segment lengths and accumulators
        self.seg_lengths = []
        self.accum = [0.0]
        total = 0.0

        for a, b in zip(self.sampled_points, self.sampled_points[1:]):
            seg_len = vec3_length(vec3_sub(b, a))
            self.seg_lengths.append(seg_len)
            total += seg_len
            self.accum.append(total)

        self.total_length = total

        # ====================================================================
        # Also update CompositeSpline subobject (+0x10)
        # This is the actual spline geometry used for interval computation
        # ====================================================================
        self._composite_spline.build_from_points(self.sampled_points)

    # ========================================================================
    # FUN_14093e5c0: Generate CylinderBoundary list
    # ========================================================================

    def build_cylinder_boundaries_14093e5c0(self, sample_count: int = 2000) -> None:
        """Generate CylinderBoundary objects from spline samples.

        Corresponds to FUN_14093e5c0.

        This method:
        1. Samples the spline at uniform parameter intervals
        2. Creates a CylinderBoundary for each pair of adjacent sample points
        3. Stores them in cylinder_boundaries list
        4. Computes bounding box (box_min, box_max)

        Args:
            sample_count: Number of sample points (default 2000 from DAT)
        """
        from .cylinder_boundary import CylinderBoundary

        self._ensure_sampled(sample_count)

        if len(self.sampled_points) < 2:
            return

        # Clear existing
        self.cylinder_boundaries = []

        # Track bounding box
        min_x, min_y, min_z = float('inf'), float('inf'), float('inf')
        max_x, max_y, max_z = float('-inf'), float('-inf'), float('-inf')

        # Create CylinderBoundary for each adjacent pair
        for i in range(len(self.sampled_points) - 1):
            p0 = self.sampled_points[i]
            p1 = self.sampled_points[i + 1]

            # Create cylinder boundary
            cylinder = CylinderBoundary.from_endpoints(p0, p1, self.radius)
            self.cylinder_boundaries.append(cylinder)

            # Update bounding box (expanded by radius)
            for point in [p0, p1]:
                min_x = min(min_x, point[0] - self.radius)
                min_y = min(min_y, point[1] - self.radius)
                min_z = min(min_z, point[2] - self.radius)
                max_x = max(max_x, point[0] + self.radius)
                max_y = max(max_y, point[1] + self.radius)
                max_z = max(max_z, point[2] + self.radius)

        # Store bounding box
        if min_x != float('inf'):
            self.box_min = (min_x, min_y, min_z)
            self.box_max = (max_x, max_y, max_z)

    # ========================================================================
    # Coordinate transformation helpers
    # ========================================================================

    def transform_spline_to_world(self) -> None:
        """将 spline 控制点从局部坐标转换为世界坐标（一次性转化）。

        在 from_region_json 创建后调用，将 spline 坐标从相对于 boundary 的局部坐标
        转换为世界坐标，后续计算直接使用世界坐标。

        注意：采样后的 sampled_points 也会失效，需要重新采样。
        """
        if self._spline_is_world:
            return  # 已经是世界坐标

        for sp in self.spline:
            sp.x += self.position_x
            sp.y += self.position_y
            sp.z += self.position_z
        self._spline_is_world = True

        # 清除已采样的点（坐标已变化）
        self.sampled_points = []
        self.seg_lengths = []
        self.accum = []
        self.total_length = 0.0

    def transform_spline_to_local(self) -> None:
        """将 spline 控制点从世界坐标转换回局部坐标（撤销转化）。

        用于需要恢复原始局部坐标的场景。
        """
        if not self._spline_is_world:
            return  # 已经是局部坐标

        for sp in self.spline:
            sp.x -= self.position_x
            sp.y -= self.position_y
            sp.z -= self.position_z
        self._spline_is_world = False

        # 清除已采样的点（坐标已变化）
        self.sampled_points = []
        self.seg_lengths = []
        self.accum = []
        self.total_length = 0.0

    def _sample_spline_uniform(self, t: float) -> tuple[float, float, float]:
        """Sample the composite spline at uniform parameter t.

        Corresponds to FUN_1402d55c0.
        Returns WORLD coordinates (after transform_spline_to_world is called).
        """
        segment_count = len(self.spline) - 1
        if segment_count <= 0:
            raise ValueError("splinetube requires at least two spline control points")

        t = clamp(t, 0.0, 1.0)
        scaled = t * segment_count
        seg_index = min(int(scaled), segment_count - 1)
        local_t = scaled - seg_index

        if t >= 1.0:
            seg_index = segment_count - 1
            local_t = 1.0

        left = self.spline[seg_index]
        right = self.spline[seg_index + 1]

        # Spline control points are now in WORLD coordinates (after transform)
        p0 = (left.x, left.y, left.z)
        p1 = (right.x, right.y, right.z)
        c0 = (left.x + left.tx * left.outlength,
              left.y + left.ty * left.outlength,
              left.z + left.tz * left.outlength)
        c1 = (right.x - right.tx * right.inlength,
              right.y - right.ty * right.inlength,
              right.z - right.tz * right.inlength)

        # Return in world coordinates
        return self._cubic_bezier(p0, c0, c1, p1, local_t)

    def _cubic_bezier(
        self,
        p0: tuple[float, float, float],
        c0: tuple[float, float, float],
        c1: tuple[float, float, float],
        p1: tuple[float, float, float],
        t: float
    ) -> tuple[float, float, float]:
        """Evaluate cubic Bezier curve."""
        omt = 1.0 - t
        omt2 = omt * omt
        omt3 = omt2 * omt
        t2 = t * t
        t3 = t2 * t

        return (
            omt3 * p0[0] + 3.0 * omt2 * t * c0[0] + 3.0 * omt * t2 * c1[0] + t3 * p1[0],
            omt3 * p0[1] + 3.0 * omt2 * t * c0[1] + 3.0 * omt * t2 * c1[1] + t3 * p1[1],
            omt3 * p0[2] + 3.0 * omt2 * t * c0[2] + 3.0 * omt * t2 * c1[2] + t3 * p1[2],
        )

    # ========================================================================
    # vtable+0x10 -> 0x14011b510: Sphere intersection test
    # ========================================================================

    def check_intersection_0x10_14011b510(
        self,
        pos: tuple[float, float, float],
        bounding_radius: float
    ) -> bool:
        """Check if sphere intersects with splinetube.

        Corresponds to vtable+0x10, function 0x14011b510.

        C++ logic (from 0x14075c250 depth > 0 branch):
        1. Transform pos from world to local coordinates:
           local_pos = (pos - position) * rotation_matrix
        2. Find nearest point on spline to local_pos
        3. Compute distance to that point
        4. Return distance < (tube_radius + bounding_radius)

        Note: After transform_spline_to_world(), spline is in world coordinates,
        so we can compare directly without coordinate transformation.

        Args:
            pos: Sphere center position in WORLD coordinates
            bounding_radius: Sphere radius

        Returns:
            True if sphere intersects tube
        """
        self._ensure_sampled()

        if not self.sampled_points:
            return False

        # Spline is now in world coordinates, compare directly
        # Find nearest distance to polyline
        dist = self._nearest_distance_to_polyline(pos)

        # Intersection if distance < (tube_radius + bounding_radius)
        return dist < (self.radius + bounding_radius)

    # ========================================================================
    # Legacy coordinate transformation (for C++ reference)
    # ========================================================================

    def _world_to_local(self, world_pos: tuple[float, float, float]) -> tuple[float, float, float]:
        """Transform world coordinates to local coordinates.

        DEPRECATED: After transform_spline_to_world(), this is no longer needed.
        Kept for C++ reference.

        Corresponds to the transformation in FUN_14075c250 depth > 0 branch:
        - Subtract position (translation)
        - Apply rotation matrix (identity for simple splinetube)

        For now, we only handle translation (no rotation).
        """
        return (
            world_pos[0] - self.position_x,
            world_pos[1] - self.position_y,
            world_pos[2] - self.position_z,
        )

    def _local_to_world(self, local_pos: tuple[float, float, float]) -> tuple[float, float, float]:
        """Transform local coordinates to world coordinates.

        DEPRECATED: After transform_spline_to_world(), this is no longer needed.
        Kept for C++ reference.

        Inverse of _world_to_local.
        """
        return (
            local_pos[0] + self.position_x,
            local_pos[1] + self.position_y,
            local_pos[2] + self.position_z,
        )

    def _nearest_distance_to_polyline(
        self,
        query: tuple[float, float, float]
    ) -> float:
        """Find nearest distance from query point to polyline.

        Corresponds to FUN_14093ed70 core logic.
        """
        best_dist = float('inf')

        for i, (a, b) in enumerate(zip(self.sampled_points, self.sampled_points[1:])):
            ab = vec3_sub(b, a)
            ab2 = vec3_dot(ab, ab)

            if ab2 <= 1e-6:
                dist = vec3_length(vec3_sub(query, a))
            else:
                t = clamp(vec3_dot(vec3_sub(query, a), ab) / ab2, 0.0, 1.0)
                closest = (
                    a[0] + ab[0] * t,
                    a[1] + ab[1] * t,
                    a[2] + ab[2] * t
                )
                dist = vec3_length(vec3_sub(query, closest))

            if dist < best_dist:
                best_dist = dist

        return best_dist

    # ========================================================================
    # vtable+0x58 -> 0x14093ed40: Lateral interval computation
    # ========================================================================

    # Sample count for interval scanning (from C++ SPLINETUBE_INTERVAL_SAMPLE_COUNT_14093ED40)
    INTERVAL_SAMPLE_COUNT = 5

    def get_lateral_interval_0x58_14093ed40(
        self,
        pos: tuple[float, float, float],
        query_radius: float
    ) -> tuple[float, float] | None:
        """Compute lateral parameter interval for splinetube.

        Corresponds to vtable+0x58, function 0x14093ed40.

        C++ code (FUN_14093ed40):
            // This is a DELEGATE wrapper that adds tube_radius to query_radius
            // and forwards to CompositeSpline<3>::vtable+0x70
            longlong spline_subobject = *(longlong *)(param_1 + 0x10);  // CompositeSpline<3> at +0x10
            float tube_radius = *(float *)(param_1 + 0x08);              // tube radius at +0x08
            float effective_radius = param_4 + tube_radius;              // query_radius + tube_radius

            // Call CompositeSpline<3>::vtable+0x70 (FUN_1414f3b30)
            (**(code **)(spline_subobject + 0x70))
                (spline_subobject, param_2, param_3, effective_radius, 5);

        This is a TWO-LAYER call:
            1. SplineTubeBoundary::get_lateral_interval_0x58 (FUN_14093ed40)
               - Adds tube_radius to query_radius
               - Forwards to CompositeSpline
            2. CompositeSpline<3>::get_parameter_interval_0x70 (FUN_1414f3b30)
               - Performs the actual spline parameter scan

        Args:
            pos: Position in WORLD coordinates
            query_radius: Query radius (55425.625 for gas fields)

        Returns normalized interval along the spline [0, 1], or None if no intersection.
        """
        self._ensure_sampled()

        # ====================================================================
        # Step 1: Compute effective_radius = query_radius + tube_radius
        # Corresponds to C++: param_4 + *(float *)(param_1 + 0x08)
        # ====================================================================
        effective_radius = query_radius + self.radius

        # ====================================================================
        # Step 2: Delegate to CompositeSpline<3>::vtable+0x70
        # Corresponds to C++: call to FUN_1414f3b30
        # ====================================================================
        return self._composite_spline.get_parameter_interval_0x70_1414f3b30(
            query=pos,
            radius=effective_radius,
            sample_count=self.INTERVAL_SAMPLE_COUNT
        )

    def _find_nearest_parameter_with_distance(
        self, query: tuple[float, float, float]
    ) -> tuple[float, float]:
        """Find normalized parameter t and distance of nearest point on spline."""
        best_dist = float('inf')
        best_t = 0.0

        for i, (a, b) in enumerate(zip(self.sampled_points, self.sampled_points[1:])):
            ab = vec3_sub(b, a)
            ab2 = vec3_dot(ab, ab)

            if ab2 <= 1e-6:
                dist = vec3_length(vec3_sub(query, a))
                t = 0.0
            else:
                local_t = clamp(vec3_dot(vec3_sub(query, a), ab) / ab2, 0.0, 1.0)
                closest = (
                    a[0] + ab[0] * local_t,
                    a[1] + ab[1] * local_t,
                    a[2] + ab[2] * local_t
                )
                dist = vec3_length(vec3_sub(query, closest))
                t = (self.accum[i] + self.seg_lengths[i] * local_t) / self.total_length

            if dist < best_dist:
                best_dist = dist
                best_t = t

        return best_t, best_dist

    def _sample_at_param(self, t: float) -> tuple[float, float, float]:
        """Sample point on polyline at normalized parameter t."""
        t = clamp(t, 0.0, 1.0)

        if t >= 1.0:
            return self.sampled_points[-1]

        target = t * self.total_length

        for i, seg_len in enumerate(self.seg_lengths):
            seg_start = self.accum[i]
            seg_end = self.accum[i + 1]

            if target <= seg_end or i == len(self.seg_lengths) - 1:
                if seg_len <= 1e-6:
                    return self.sampled_points[i]

                local_t = clamp((target - seg_start) / seg_len, 0.0, 1.0)
                a = self.sampled_points[i]
                b = self.sampled_points[i + 1]
                return (
                    a[0] + (b[0] - a[0]) * local_t,
                    a[1] + (b[1] - a[1]) * local_t,
                    a[2] + (b[2] - a[2]) * local_t,
                )

        return self.sampled_points[-1]

    def _find_nearest_parameter(self, query: tuple[float, float, float]) -> float:
        """Find normalized parameter t of nearest point on spline."""
        t, _ = self._find_nearest_parameter_with_distance(query)
        return t

    # ========================================================================
    # vtable+0x70 -> 0x14093ee10: Radial interval computation
    # ========================================================================

    def get_radial_interval_0x70_14093ee10(
        self,
        pos: tuple[float, float, float],
        query_radius: float
    ) -> tuple[float, float]:
        """Compute radial interval normalized by tube radius.

        Corresponds to vtable+0x70, function 0x14093ee10.

        C++ implementation (FUN_14093ee10):
            // Step 1: Get lateral interval via vtable+0x58
            (**(code **)(*param_1 + 0x58))(param_1, local_res8);
            // local_res8[0] = lateral_lower, local_res8[1] = lateral_upper

            // Step 2: Sample representative point using lateral_lower
            // param_1[2] is CompositeSpline at +0x10
            // vtable+0x08 is sample method
            pfVar1 = (float *)(**(code **)(param_1[2] + 8))(param_1 + 2, local_68, local_res8[0]);

            // Step 3: Compute distance from query to representative point
            distance = sqrt(sum((pfVar1[i] - param_3[i])^2 for i in 0..2))

            // Step 4: Compute radial interval
            tube_radius = *(float *)(param_1 + 0x0c);
            lower = max((distance - query_radius) / tube_radius, 0.0);
            upper = min((distance + query_radius) / tube_radius, 1.0);

        This is a TWO-STEP process:
            1. Call get_lateral_interval_0x58 to get parameter range
            2. Use lateral_lower to sample a representative point
            3. Compute distance and normalize by tube_radius

        Args:
            pos: Position in WORLD coordinates
            query_radius: Query radius (55425.625 for gas)

        Returns (lower, upper) where values are in [0, 1].
        """
        self._ensure_sampled()

        if self.radius <= 0:
            return (0.0, 1.0)

        # ====================================================================
        # Step 1: Get lateral interval (vtable+0x58)
        # ====================================================================
        lateral_interval = self.get_lateral_interval_0x58_14093ed40(pos, query_radius)

        if lateral_interval is None:
            return (0.0, 1.0)

        lateral_lower, lateral_upper = lateral_interval

        # ====================================================================
        # Step 2: Sample representative point using lateral_lower
        # Corresponds to C++: sample at local_res8[0] (lateral_lower)
        # ====================================================================
        representative_point = self._composite_spline.sample_0x08_1402d55c0(lateral_lower)

        # ====================================================================
        # Step 3: Compute distance from query to representative point
        # ====================================================================
        diff = vec3_sub(representative_point, pos)
        distance = vec3_length(diff)

        # ====================================================================
        # Step 4: Compute radial interval normalized by tube_radius
        # ====================================================================
        lower = (distance - query_radius) / self.radius
        upper = (distance + query_radius) / self.radius

        # Clamp to [0, 1]
        lower = max(0.0, lower)
        upper = min(1.0, upper)

        if lower > upper:
            lower = upper

        return (lower, upper)

    # ========================================================================
    # vtable+0x78 -> 0x14093efc0: Volume computation
    # ========================================================================

    def get_volume_0x78_14093efc0(self) -> float:
        """Compute tube volume.

        Corresponds to vtable+0x78, function 0x14093efc0.

        Formula:
            Volume = spline_length * π * tube_radius²

        Returns:
            Tube volume
        """
        self._ensure_sampled()

        if self.total_length <= 0 or self.radius <= 0:
            return 0.0

        # π = 0x40490fdb
        pi = 3.14159265358979323846
        return self.total_length * pi * self.radius * self.radius

    # ========================================================================
    # Unified interface (for external callers like BoundaryList)
    # vtable slots are same offset across all Boundary subclasses
    # ========================================================================

    def check_intersection_0x10(self, pos: tuple[float, float, float], bounding_radius: float) -> bool:
        """Unified interface at vtable+0x10 - forwards to implementation."""
        return self.check_intersection_0x10_14011b510(pos, bounding_radius)

    def get_lateral_interval_0x58(self, pos: tuple[float, float, float], query_radius: float) -> tuple[float, float] | None:
        """Unified interface at vtable+0x58 - forwards to implementation."""
        return self.get_lateral_interval_0x58_14093ed40(pos, query_radius)

    def get_radial_interval_0x70(self, pos: tuple[float, float, float], query_radius: float) -> tuple[float, float]:
        """Unified interface at vtable+0x70 - forwards to implementation."""
        return self.get_radial_interval_0x70_14093ee10(pos, query_radius)

    def get_volume_0x78(self) -> float:
        """Unified interface at vtable+0x78 - forwards to implementation."""
        return self.get_volume_0x78_14093efc0()

    # ========================================================================
    # Placeholder methods for other vtable slots
    # ========================================================================

    def placeholder_0x00(self) -> None:
        """vtable+0x00: Destructor placeholder."""
        pass

    def placeholder_0x08(self) -> None:
        """vtable+0x08 placeholder."""
        pass

    def placeholder_0x18(self) -> None:
        """vtable+0x18 placeholder."""
        pass

    def placeholder_0x20(self) -> None:
        """vtable+0x20 placeholder."""
        pass

    def placeholder_0x28(self) -> None:
        """vtable+0x28 placeholder."""
        pass

    def placeholder_0x30(self) -> None:
        """vtable+0x30 placeholder."""
        pass

    def placeholder_0x38(self) -> None:
        """vtable+0x38 placeholder."""
        pass

    def placeholder_0x40(self) -> None:
        """vtable+0x40 placeholder."""
        pass

    def placeholder_0x48(self) -> bool:
        """vtable+0x48: has_lateral_falloff placeholder."""
        return True

    def placeholder_0x50(self) -> None:
        """vtable+0x50 placeholder."""
        pass

    def placeholder_0x60(self) -> bool:
        """vtable+0x60: has_radial_falloff placeholder."""
        return True

    def placeholder_0x68(self) -> None:
        """vtable+0x68 placeholder."""
        pass

    # ========================================================================
    # Factory methods
    # ========================================================================

    @classmethod
    def from_region_json(
        cls,
        region_data: dict,
        area_position: tuple[float, float, float] | None = None
    ) -> 'SplineTubeBoundary':
        """Create SplineTubeBoundary from regions.json data.

        Args:
            region_data: Region dict from regions.json
            area_position: Optional position from resourceareas.json (x, y, z)
                          If provided, spline points will be offset by this position

        Returns:
            SplineTubeBoundary instance
        """
        boundary = region_data.get('boundary', {})
        boundary_size = boundary.get('size', {})

        # Get radius
        radius = float(boundary_size.get('r', 0.0))

        # Get spline control points (LOCAL coordinates from regions.json)
        spline_data = boundary.get('spline', [])
        spline = [
            SplineControlPoint(
                x=float(sp.get('x', 0)),
                y=float(sp.get('y', 0)),
                z=float(sp.get('z', 0)),
                tx=float(sp.get('tx', 0)),
                ty=float(sp.get('ty', 0)),
                tz=float(sp.get('tz', 0)),
                inlength=float(sp.get('inlength', 0)),
                outlength=float(sp.get('outlength', 0)),
            )
            for sp in spline_data
        ]

        # Get position from area_position or region_data
        if area_position:
            pos_x, pos_y, pos_z = area_position
        else:
            pos_x = float(region_data.get('position_x', 0) or 0)
            pos_y = float(region_data.get('position_y', 0) or 0)
            pos_z = float(region_data.get('position_z', 0) or 0)

        instance = cls(
            position_x=pos_x,
            position_y=pos_y,
            position_z=pos_z,
            radius=radius,
            spline=spline,
        )

        # Transform spline to world coordinates
        instance.transform_spline_to_world()

        return instance